/*
 * Created by SharpDevelop.
 * User: ZHANITEST
 * Date: 2019-07-14
 * Time: 오전 12:01
 * 
 * To change this template use Tools | Options | Coding | Edit Standard Headers.
 */
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Windows.Forms;
using Snapping;

namespace Snapping
{
	/// <summary>
	/// Description of MainForm.
	/// </summary>
	public partial class MainForm : Form
	{
		public MainForm()
		{
			//
			// The InitializeComponent() call is required for Windows Forms designer support.
			//
			InitializeComponent();
			
			//
			// TODO: Add constructor code after the InitializeComponent() call.
			//
		}
		
		void MainFormLoad(object sender, EventArgs e)
		{
			EventHelper logicObj = new EventHelper();
			
			string cpu_name = logicObj.getCpuName();
			string gpu_name = logicObj.getGpuName();
			string ram_cpct = logicObj.getRamCapacity();
			string win_spec = logicObj.getWindowsName() + (logicObj.getServicePackName()=="" ? "":" / "+logicObj.getServicePackName() );
			string[] ports  = logicObj.getPortNames();
			string port_txt = logicObj.getPortNames("\n");
			
			// Pretty View
			tbCpu.Text = cpu_name;
			tbGpu.Text = gpu_name;
			tbRam.Text = ram_cpct;
			tbOs.Text  = win_spec;
			lbPorts.Items.Clear();
			foreach(string port in ports){
				lbPorts.Items.Add(port);
			}
			
			string now_txt = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss");
			
			lbStatus.Text = "Update! - " + now_txt;
			
			// Plain Text Output
			string report_txt = "";
			report_txt += "Generated By Snapping [ "+now_txt+" ]\n";
			report_txt += "\n---[CPU]------------------------------------------------------------------------\n";
			report_txt += cpu_name+"\n";
			report_txt += "\n---[GPU]------------------------------------------------------------------------\n";
			report_txt += gpu_name+"\n";
			report_txt += "\n---[RAM]------------------------------------------------------------------------\n";
			report_txt += ram_cpct+"\n";
			report_txt += "\n---[OS/Service Pack Info]-------------------------------------------------------\n";
			report_txt += win_spec+"\n";
			report_txt += "\n---[Opened serial port]---------------------------------------------------------\n";
			report_txt += port_txt+"\n";			
			
			rtbReport.Text = report_txt;
				
		}
		
		void Button1Click(object sender, EventArgs e)
		{
			InfoForm infoForm = new InfoForm();
			infoForm.ShowDialog();
		}
		
		void BtnRefreshClick(object sender, EventArgs e)
		{
			lbStatus.Text = "Wait...";
			
			EventHelper logicObj = new EventHelper();
			
			string cpu_name = logicObj.getCpuName();
			string gpu_name = logicObj.getGpuName();
			string ram_cpct = logicObj.getRamCapacity();
			string win_spec = logicObj.getWindowsName() + (logicObj.getServicePackName()=="" ? "":" / "+logicObj.getServicePackName() );
			string[] ports  = logicObj.getPortNames();
			string port_txt = logicObj.getPortNames("\n");
			
			// Pretty View
			tbCpu.Text = cpu_name;
			tbGpu.Text = gpu_name;
			tbRam.Text = ram_cpct;
			tbOs.Text  = win_spec;
			lbPorts.Items.Clear();
			foreach(string port in ports){
				lbPorts.Items.Add(port);
			}
			
			string now_txt = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss");
			
			lbStatus.Text = "Update! - " + now_txt;
			
			// Plain Text Output
			string report_txt = "";
			report_txt += "Generated By Snapping [ "+now_txt+" ]\n";
			report_txt += "\n---[CPU]------------------------------------------------------------------------\n";
			report_txt += cpu_name+"\n";
			report_txt += "\n---[GPU]------------------------------------------------------------------------\n";
			report_txt += gpu_name+"\n";
			report_txt += "\n---[RAM]------------------------------------------------------------------------\n";
			report_txt += ram_cpct+"\n";
			report_txt += "\n---[OS/Service Pack Info]-------------------------------------------------------\n";
			report_txt += win_spec+"\n";
			report_txt += "\n---[Opened serial port]---------------------------------------------------------\n";
			report_txt += port_txt+"\n";			
			
			rtbReport.Text = report_txt;
		}

		void BtnOutTextClick(object sender, EventArgs e)
		{
			string report = rtbReport.Text;
			System.IO.File.WriteAllText("report.txt", report);
			MessageBox.Show("Done!");
			
		}
	}
}
